# Site settings
title: #Mali100Méga
email: rgaudin@gmail.com
description: "Pour une augmentation des débits Internet au Mali"
baseurl: ""
url: "http://100mega.ml"
twitter_username: zirasun

# Build settings
markdown: kramdown
permalink: pretty
